name: Un_title
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  intl: ^0.18.1
  device_info_plus: ^9.0.2
  app_settings: ^5.0.0
  open_file: ^3.3.2
  chat_bubbles: ^1.5.0
  flutter_tts: ^3.8.5
  shared_preferences: ^2.2.2
  pdf_render: ^1.4.12
  speech_to_text: ^6.3.0
  dynamic_color: ^1.6.8
  syncfusion_flutter_pdf: ^22.2.12
  flutter_markdown: ^0.6.10
  google_fonts: ^6.1.0
  groq: ^0.0.7
  flutter_face_api: ^6.1.1
  flutter_face_core_basic: ^6.1.0
  image_picker: ^1.0.7
  appwrite: ^12.0.1
  google_mlkit_face_detection: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/vocab.txt
    - assets/mobilebert_model.tflite
    - assets/icons/

  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/playstore.png"  # Path to your icon image
# Flutter Launcher Icons configuration
# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/icons/playstore.png"
#   min_sdk_android: 21
#   adaptive_icon_background: "#00A4E4" # UCSS blue background color
#   adaptive_icon_foreground: "assets/icons/playstore.png"
#   remove_alpha_ios: true
#   web:
#     generate: false
#   windows:
#     generate: false
#   macos:
#     generate: false
